[tox]
envlist =
    py{310,311,312}-dj42-{sqlite,postgres}-taggit2
    py{310,311,312,313,314}-dj52-{sqlite,postgres}-taggit2
    py{312,313,314}-dj{60,master}-{sqlite,postgres}-taggit2

[testenv]
allowlist_externals = ./runtests.py
commands = ./runtests.py --noinput {posargs}

basepython =
    py310: python3.10
    py311: python3.11
    py312: python3.12
    py313: python3.13
    py314: python3.14

deps =
    taggit2: django-taggit>=2.0
    dj42: django~=4.2.0
    dj52: django~=5.2.0
    dj60: django~=6.0.0
    djmaster: git+https://github.com/django/django.git@main#egg=Django
    postgres: psycopg>=3.1

setenv =
    postgres: DATABASE_ENGINE=django.db.backends.postgresql

[testenv:future]
allowlist_externals = ./runtests.py
commands = ./runtests.py --noinput {posargs}
deps =
    git+https://github.com/django/django.git@main#egg=Django
    git+https://github.com/jazzband/django-taggit@master#egg=django-taggit
