# Generated by Django 2.1 on 2018-08-07 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0006_auto_20171109_0614'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeafoodRestaurant',
            fields=[
                ('restaurant_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tests.Restaurant')),
            ],
            options={
                'abstract': False,
            },
            bases=('tests.restaurant',),
        ),
        migrations.AddField(
            model_name='bandmember',
            name='favourite_restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tests.Restaurant'),
        ),
        migrations.AlterUniqueTogether(
            name='bandmember',
            unique_together={('band', 'name')},
        ),
    ]
