# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-20 10:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0008_prefetch_related_tests'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='related_articles',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='_article_related_articles_+', serialize=False, to='tests.Article'),
        ),
        migrations.AddField(
            model_name='article',
            name='view_count',
            field=models.IntegerField(blank=True, null=True, serialize=False),
        ),
    ]
