# Generated by Django 4.2.9 on 2024-02-04 06:59

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ("taggit", "0005_auto_20220424_2025"),
        ("tests", "0011_add_room_features"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecordLabel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("range", models.SmallIntegerField(blank=True, default=5)),
            ],
        ),
        migrations.AddField(
            model_name="album",
            name="label",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tests.recordlabel",
            ),
        ),
    ]
