# Generated by Django 4.0.3 on 2022-03-24 20:39

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0004_alter_taggeditem_content_type_alter_taggeditem_tag'),
        ('tests', '0011_add_room_features'),
    ]

    operations = [
        migrations.CreateModel(
            name='BandManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('band', modelcluster.fields.ParentalOneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manager', to='tests.band')),
            ],
        ),
    ]
